<script setup lang="ts">
import { ref, onMounted } from "vue";
import ProglangBar from "./ProglangBar.vue";

const langs = ref<{
    name: string;
    percentage: number;
}[]>([]);
onMounted(async ()=> {
    const response = await fetch("/performance.svg");
    if(!response.ok)
        return;

    const svgString = await response.text();
    const parser = new DOMParser();
    const doc = parser.parseFromString(svgString, "image/svg+xml");
    const nodes = doc.querySelectorAll("text.lang-name");

    langs.value = Array.from(nodes).map(node => {
        const text = node.textContent?.trim() || "";
        const idx = text.lastIndexOf(" ");

        return {
            name: text.slice(0, idx),
            percentage: parseFloat(text.slice(idx + 1).slice(0, -1)),
        };
    });
});
</script>

<template>
    <h3 class="d-block fw-bold mt-4 shimmer" id="expertise">Expertise</h3>
    <hr/>

    <h4 class="d-block fw-bold mt-4">Most Used Languages</h4>
    <p>My most used languages below are based and automatically generated by <a target="_blank" href="https://github-readme-stats.vercel.app/api/top-langs/?username=nthnn&layout=compact&theme=onedark&hide_border=true&title_color=e9ecef&text_color=e9ecef&bg_color=272b30&hide=html,css,batchfile,jupyter+notebook,shell,cmake&langs_count=20&size_weight=0.5&count_weight=0.5">github-readme-stats</a>, and will be updated every week.</p>
    <br/>

    <div class="row row-cols-1 row-cols-md-2 g-3">
        <div
            class="col"
            v-for="(lang, index) in langs"
            :key="lang.name"
            :class="{ 'desktop-only': index >= langs.length - 10 }">
            <ProglangBar
                :name="lang.name"
                :progress="lang.percentage" />
        </div>
    </div>
    <hr/>

    <h4 class="d-block fw-bold mt-4">Contribution Graph</h4>
    <p>This contribution graph shows last 30 days' amount of contribution on GitHub for each day. Automatically generated via <a target="_blank" href="https://github-readme-activity-graph.vercel.app/graph?username=nthnn&custom_title=Nathanne%20Isip%27s%20Contribution%20Graph&hide_border=true&theme=react-dark&bg_color=272b30&color=ffffff">github-readme-activity-graph</a></p>
    <img src="https://github-readme-activity-graph.vercel.app/graph?username=nthnn&custom_title=Nathanne%20Isip%27s%20Contribution%20Graph&hide_border=true&theme=react-dark&bg_color=1a1a1a&color=ffffff" class="w-100 mt-2 d-block" />

    <br/>
</template>
